version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 8090:5432
    volumes:
      - ./intialise_test_db/postgres.sql:/docker-entrypoint-initdb.d

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: example
    ports:
      - 8091:1433
    volumes:
      - ./intialise_test_db/postgres.sql:/docker-entrypoint-initdb.d
